### ISSUE TITLE
compilation of gomobile helper

### ISSUE THREAD

**Issue by ghost** [archanpaul/medium-flutter_with_go#1]
Thanks for your code on bitbucket !.

I also am interested in using gomobiel with flutter.

Check out this: https://github.com/worldiety/goup

It helps with cross platform compilation. With the NDK you need to cross compile against it and the right version of android NDK.This helps do that in a declarative way !

**Comment by archanpaul** [comment]
> Check out this: https://github.com/worldiety/goup

Thanks for sharing the link. Your https://github.com/worldiety/std project is also quite useful. We internally use similar constructs apart from JSON for data serialization in gomobile for incompatible types.
