### ISSUE TITLE
Golang for Flutter desktop (macos)

### ISSUE THREAD

**Issue by ganeshrvel** [archanpaul/medium-flutter_with_go#2]
I have been following your tutorial to setup a project in flutter that work along with golang. But unfortunately it doesn't describe how to use GoLang along with Flutter for desktop (macos).

Could you guide? I had tried all resources available online (which is only a few) and nothing seems to be working for flutter. 

Thanks

**Comment by archanpaul** [comment]
I don't think gomobile can be used for Flutter for macos because it
generates only Android and iOS libraries. For desktop, you should check
https://flutter.dev/docs/development/platform-integration/c-interop As far
as I know, it does not support Go yet.
